
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public GamePlot.TbtestPlot_0101 TbtestPlot0101 {get; }
    public GamePlot.TbtestPlot_0201 TbtestPlot0201 {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbtestPlot0101 = new GamePlot.TbtestPlot_0101(loader("gameplot_tbtestplot_0101"));
        TbtestPlot0201 = new GamePlot.TbtestPlot_0201(loader("gameplot_tbtestplot_0201"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbtestPlot0101.ResolveRef(this);
        TbtestPlot0201.ResolveRef(this);
    }
}

}
